//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('transactions')
export class transactionsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  medicationId: number;

  @Column('integer', { nullable: true })
  quantityDispensed: number;

  @Column('integer', { nullable: true })
  remainingQuantity: number;

  @Column('real', { nullable: true })
  totalCost: number;
}
