//Source code generated by AppGPT (www.appgpt.tech)
let data: any = {
  defaultData: {
    medications: [
      {
        name: 'name 1',
        description: 'description 1',
        quantityInStock: 1,
        minQuantityForAlert: 1,
        id: 3,
      },
      {
        name: 'name 2',
        description: 'description 2',
        quantityInStock: 2,
        minQuantityForAlert: 2,
        id: 36,
      },
      {
        name: 'name 3',
        description: 'description 3',
        quantityInStock: 3,
        minQuantityForAlert: 3,
        id: 74,
      },
      {
        name: 'name 4',
        description: 'description 4',
        quantityInStock: 4,
        minQuantityForAlert: 4,
        id: 46,
      },
      {
        name: 'name 5',
        description: 'description 5',
        quantityInStock: 5,
        minQuantityForAlert: 5,
        id: 39,
      },
    ],
    transactions: [
      {
        medicationId: 1,
        quantityDispensed: 1,
        remainingQuantity: 1,
        totalCost: 0.88,
        id: 18,
      },
      {
        medicationId: 2,
        quantityDispensed: 2,
        remainingQuantity: 2,
        totalCost: 0.26,
        id: 66,
      },
      {
        medicationId: 3,
        quantityDispensed: 3,
        remainingQuantity: 3,
        totalCost: 0.22,
        id: 6,
      },
      {
        medicationId: 4,
        quantityDispensed: 4,
        remainingQuantity: 4,
        totalCost: 0.79,
        id: 75,
      },
      {
        medicationId: 5,
        quantityDispensed: 5,
        remainingQuantity: 5,
        totalCost: 0.22,
        id: 24,
      },
    ],
    notifications: [
      { medicationId: 1, message: 'message 1', id: 23 },
      { medicationId: 2, message: 'message 2', id: 79 },
      { medicationId: 3, message: 'message 3', id: 23 },
      { medicationId: 4, message: 'message 4', id: 60 },
      { medicationId: 5, message: 'message 5', id: 92 },
    ],
  },
};
export default data;
