//Source code generated by AppGPT (www.appgpt.tech)
import { mergeTranslations } from 'ra-core';
import polyglotI18nProvider from 'ra-i18n-polyglot';
import enOriginal from 'ra-language-english';
import frOriginal from 'ra-language-french';

const enResources = {
  resources: {
    medications: {
      name: 'Medications',
      fields: {
        name: 'Name',
        description: 'Description',
        quantityInStock: 'Quantity In Stock',
        minQuantityForAlert: 'Min Quantity For Alert',
        id: 'id',
      },
    },
    transactions: {
      name: 'Transactions',
      fields: {
        medicationId: 'Medication Id',
        quantityDispensed: 'Quantity Dispensed',
        remainingQuantity: 'Remaining Quantity',
        totalCost: 'Total Cost',
        id: 'id',
      },
    },
    notifications: {
      name: 'Notifications',
      fields: { medicationId: 'Medication Id', message: 'Message', id: 'id' },
    },
  },
};
const frResources = {
  resources: {
    medications: {
      name: 'Medications (fr)',
      fields: {
        name: 'Name (fr)',
        description: 'Description (fr)',
        quantityInStock: 'Quantity In Stock (fr)',
        minQuantityForAlert: 'Min Quantity For Alert (fr)',
        id: 'id',
      },
    },
    transactions: {
      name: 'Transactions (fr)',
      fields: {
        medicationId: 'Medication Id (fr)',
        quantityDispensed: 'Quantity Dispensed (fr)',
        remainingQuantity: 'Remaining Quantity (fr)',
        totalCost: 'Total Cost (fr)',
        id: 'id',
      },
    },
    notifications: {
      name: 'Notifications (fr)',
      fields: {
        medicationId: 'Medication Id (fr)',
        message: 'Message (fr)',
        id: 'id',
      },
    },
  },
};

const en = mergeTranslations(enOriginal, enResources);
const fr = mergeTranslations(frOriginal, frResources);

const translations = { en, fr };
export const i18nProvider = polyglotI18nProvider(
  (locale) => translations[locale],
  'en', //default locale
  [
    { locale: 'en', name: 'English' },
    { locale: 'fr', name: 'Français' },
  ],
);
